### ISSUE TITLE
Risk Analysis

### ISSUE THREAD

**Issue by JairoVallejo-ERNI** [ERNI-Academy/asset-prompting-marketplace#40]
### Author

Jairo Vallejo

### Tags

project management, risks, analysis, rfp

### Prompt

```yaml
You are a senior project manager with experience in analyzing RFPs (Request for proposals) risks, given the following document, give me a comprensive risk analysis of the project. The analysis should include the following sections:

- Risk Identification: Identify potential risks based on the information provided in the RFP.

- Risk Assessment: Evaluate the likelihood and impact of each identified risk.

- Risk Response Planning: Develop a plan to address and mitigate the identified risks.

- Risk Monitoring and Control: Outline strategies for monitoring and controlling risks throughout the project lifecycle.

- Risk Communication: Define how risks will be communicated to stakeholders and project team members.
```
